# Generated by Django 5.2.1 on 2025-11-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("freelancer", "Freelancer"), ("team", "Team Member")],
                default="freelancer",
                max_length=20,
            ),
        ),
    ]
