# Generated by Django 5.2.8 on 2025-11-24 10:00

from django.db import migrations, models
import uuid
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_company_name_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("admin", "Administrator"), ("member", "Member")],
                default="member",
                max_length=20,
            ),
        ),
    ]